#!name=My Shadowsocks
#!desc=My VPS Shadowsocks Node
#!system=Quantumult X

[server_remote]
shadowsocks=My-SS,168.107.31.175,27350,chacha20-ietf-poly1305,"vM9@7qLp2!Za",udp-relay=true,fast-open=false
